server:
  port: 8081

spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:mem:testdb
    username: demo
    password:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE





