server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: demo
    password:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always

logging.level.hibernate.SQL: debug
logging.level.hibernate.type.descriptor.sql: trace




